export const WISHLIST_ADD_ITEM = 'WISHLIST_ADD_ITEM';
export const WISHLIST_REMOVE_ITEM = 'WISHLIST_REMOVE_ITEM';
export const WISHLIST_CLEAR = 'WISHLIST_CLEAR';
export const WISHLIST_SAVE = 'WISHLIST_SAVE';
